version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo Installing source NPM dependencies...

  pre_build:
    commands:
      - npm i
      - npm install -g serve
      - npm i -g typescript

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`
      - serve -s build

artifacts:
  files:
    - "**/*"
  base-directory: "build"
  discard-paths: yes

cache:
  paths:
    - "node_modules/**/*"
