version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo Installing source NPM dependencies...

  pre_build:
    commands:
      - npm ci
      - npm install -g serve
      - npm i -g typescript

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - serve -s build -l 80 -n 3.105.157.204

artifacts:
  type: zip
  files:
    - "**/*"
