version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo Installing source NPM dependencies...

  pre_build:
    commands:
      - sudo npm ci
      - sudo npm install -g serve
      - npm install react-scripts@5.0.1 -g
      - npm install typescript@4.9.5 -g

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: build
